version: '3'
services:
  nodeweb:
    build: ./consumerjs
    links:
    - kafka
    ports:
    - "3000:3000"
  producer:
    build: ./producer
    # volumes:
    # - .:/code
    # - logvolume01:/var/log
    tty: true
    links:
    - kafka
  consumer:
    build: ./consumer
    # volumes:
    # - .:/code
    # - logvolume01:/var/log
    tty: true
    links:
    - kafka
  kafka:
    image: spotify/kafka
    hostname: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    ports:
    - "9092:9092"
    - "2181:2181"